# -*- coding: utf-8 -*-
"""spam sms detection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l82IRQUVtA54KNKfRJbI45AIKEgKHtYR
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load CSV
df = pd.read_csv('spam.csv', encoding='ISO-8859-1')

# Keep only relevant columns
df = df[['v1', 'v2']]
df.columns = ['label', 'text']

# Map labels to 0 (ham) and 1 (spam)
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

df.head()

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, random_state=42)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

# Naive Bayes
nb_model = MultinomialNB()
nb_model.fit(X_train_vec, y_train)

# Logistic Regression
lr_model = LogisticRegression()
lr_model.fit(X_train_vec, y_train)

from sklearn.metrics import classification_report, accuracy_score

# Naive Bayes
nb_preds = nb_model.predict(X_test_vec)
print("\n🔍 Naive Bayes Results")
print("Accuracy:", accuracy_score(y_test, nb_preds))
print(classification_report(y_test, nb_preds))

# Logistic Regression
lr_preds = lr_model.predict(X_test_vec)
print("\n🔍 Logistic Regression Results")
print("Accuracy:", accuracy_score(y_test, lr_preds))
print(classification_report(y_test, lr_preds))

def predict_sms(text):
    cleaned = vectorizer.transform([text])
    pred = nb_model.predict(cleaned)[0]
    print("\n🧠 Prediction:", "📩 SPAM" if pred == 1 else "✅ HAM")

# Example
msg = input("Enter an SMS Email Message to classify: ")
predict_sms(msg)